name: tickets
description: Katum Tickets on BlockChain

version: 1.0.0+4

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  toast: ^0.1.4
  flutter_icons: ^0.1.4
  pinput: ^0.1.7
  intl: ^0.15.8
  flip_card: ^0.3.0
  fast_qr_reader_view: ^0.1.5
  vibration: ^1.1.0
  location: ^2.3.5
  web3dart: ^1.0.0
  flutter_webview_plugin: ^0.3.5
  flutter_widget_gallery: ^0.1.2
  firebase_messaging: ^5.0.4
  flutter_facebook_login: ^2.0.1
  google_sign_in: ^4.0.2
  morpheus: ^0.8.1
  url_launcher: ^5.0.3
  share: ^0.6.1+1
  google_maps_flutter: ^0.5.18
  shared_preferences: ^0.5.3+1
  flutter_spinkit: ^3.1.0
  dio: ^2.1.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/img/cover.png
      - assets/img/title.png
      - assets/google.png
      - assets/home.png
      - assets/map.png
      - assets/t.gif
      - assets/avatars/avatar-1.jpg
      - assets/avatars/avatar-2.jpg
      - assets/avatars/avatar-3.jpg
      - assets/avatars/avatar-4.jpg
      - assets/avatars/avatar-5.jpg
      - assets/avatars/avatar-6.jpg

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
